run tests only on master branch

diff --git a/.github/workflows/dotnet.yml b/.github/workflows/dotnet.yml
--- a/.github/workflows/dotnet.yml
+++ b/.github/workflows/dotnet.yml
@@ -28,12 +28,13 @@ jobs:
     - name: Build
       run: dotnet build --no-restore
     - name: Test
+      if: github.ref == 'refs/heads/master'
       env:
         SITECORESEND__APIKEY: ${{ secrets.SITECORESEND__APIKEY }}
         SITECORESEND__TESTLISTID: ${{ secrets.SITECORESEND__TESTLISTID }}
       run: dotnet test --no-build --verbosity normal --logger "trx;LogFileName=test-results.trx"
     - name: Test Reporter
-      if: success() || failure()    # run this step even if previous step failed
+      if: github.ref == 'refs/heads/master' && (success() || failure())   # run this step even if previous step failed
       uses: bibipkins/dotnet-test-reporter@v1.4.0
       with:
         github-token: ${{ secrets.GITHUB_TOKEN }}
