add test report and split jobs

diff --git a/.github/workflows/dotnet.yml b/.github/workflows/dotnet.yml
--- a/.github/workflows/dotnet.yml
+++ b/.github/workflows/dotnet.yml
@@ -15,7 +15,6 @@ defaults:
 
 jobs:
   build:
-
     runs-on: ubuntu-latest
     environment: test
     steps:
@@ -32,4 +31,13 @@ jobs:
       env:
         SITECORESEND__APIKEY: ${{ secrets.SITECORESEND__APIKEY }}
         SITECORESEND__TESTLISTID: ${{ secrets.SITECORESEND__TESTLISTID }}
-      run: dotnet test --no-build --verbosity normal
+      run: dotnet test --no-build --verbosity normal --logger "trx;LogFileName=test-results.trx"
+    - name: Test Reporter
+      if: success() || failure()    # run this step even if previous step failed
+      uses: bibipkins/dotnet-test-reporter@v1.4.0
+      with:
+        github-token: ${{ secrets.GITHUB_TOKEN }}
+        comment-title: 'Unit Test Results'
+        results-path: ./**/*.trx
+#        coverage-path: ./TestResults/coverage.xml
+#        coverage-threshold: 80
